# Generated by Django 3.1.7 on 2021-03-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('packing', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('batch_no', models.CharField(max_length=100)),
            ],
        ),
    ]
