# Generated by Django 3.1.7 on 2021-03-02 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0002_brand_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backstore.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backstore.dealer'),
            preserve_default=False,
        ),
    ]
