# Generated by Django 3.1.7 on 2021-03-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0004_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='regist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
    ]
