# Generated by Django 3.1.7 on 2021-06-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0006_auto_20210403_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expiring_medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('batch_no', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('cost', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstore.brand')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstore.dealer')),
            ],
        ),
    ]
