# Generated by Django 3.1.7 on 2021-06-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0007_expiring_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiring_medicines',
            name='packing',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expiring_medicines',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expiring_medicines',
            name='selling_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
