# Generated by Django 3.1.7 on 2021-06-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0008_auto_20210611_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiring_medicines',
            name='brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expiring_medicines',
            name='dealer',
            field=models.CharField(max_length=200),
        ),
    ]
