# Generated by Django 3.1.7 on 2021-06-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0009_auto_20210611_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dealer', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('packing', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('batch_no', models.CharField(max_length=100)),
            ],
        ),
    ]
