# Generated by Django 3.1.7 on 2021-06-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstore', '0010_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expiring_medicines',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
